use_frameworks!

target 'Tango_Example' do
  pod 'Tango', :path => '../'

  target 'Tango_Tests' do
    inherit! :search_paths

    
  end
end

target 'Tango_Example_Rich_Notification' do
  pod 'TangoRichNotification', :path => '../'
end
